version: '2'
services:
    automation-app:
        image: automation
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://automation-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Automation
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8083:8083
    automation-mongodb:
        extends:
            file: mongodb.yml
            service: automation-mongodb
